buildCommand: |
  pip install --upgrade pip setuptools wheel
  pip install -r requirements.txt

services:
  - type: web
    name: students-performance-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    runtime: python3.9
